dist: trusty
sudo: required
language: c
env:
 global:
 - OCAML_MIN=4.02.3
 - OCAML_MAX=4.06.0
 - DEPS="camlp5 ocamlfind ppx_tools_versioned ppx_deriving ocaml-migrate-parsetree re"
 - JOBS=2

install:
 - opam init -j $JOBS --compiler=$OCAML_MIN -n -y
 - eval $(opam config env)
 - opam config var root
 - opam install -j $JOBS -y $DEPS
 - opam list
 - opam switch $OCAML_MAX -y
 - eval $(opam config env)
 - opam install -j $JOBS -y $DEPS
 - opam list

matrix:
  include:

  - env: TEST="linux build $OCAML_MIN"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
        - lua5.1
        - gnuplot
        - gcc-multilib
    cache:
      apt: true
      directories:
      - $HOME/.opam
    script:
    - opam switch $OCAML_MIN
    - make
    - make -C bench
    - make byte

  - env: TEST="linux build $OCAML_MAX"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
        - lua5.1
        - gnuplot
        - gcc-multilib
    cache:
      apt: true
      directories:
      - $HOME/.opam
    script:
    - opam switch $OCAML_MAX
    - make
    - make -C bench
    - make byte
    
  - env: TEST="osx build $OCAML_MIN"
    os: osx
    before_install:
    - brew update
    - brew install --ignore-dependencies opam
    - brew install gnu-time
    - brew install lua51
    cache:
      directories:
      - $HOME/.opam
    script:
    - opam switch $OCAML_MIN
    - make
    - make -C bench
    - make byte

  - env: TEST="osx build $OCAML_MAX"
    os: osx
    before_install:
    - brew update
    - brew install --ignore-dependencies opam
    - brew install gnu-time
    - brew install lua51
    cache:
      directories:
      - $HOME/.opam
    script:
    - opam switch $OCAML_MAX
    - make
    - make -C bench
    - make byte

  - env: TEST="opam package installation"
    os: linux
    addons:
      apt:
        sources:
        - avsm
        packages:
        - opam
        - lua5.1
        - gnuplot
        - gcc-multilib
    script:
    - opam pin -y add elpi "https://github.com/${TRAVIS_REPO_SLUG}.git#${TRAVIS_COMMIT}"
    - ocamlfind query elpi
    - ls `ocamlfind printconf destdir`/elpi
    - which elpi
    - opam remove elpi
    - opam pin -y remove elpi
    - if ocamlfind query elpi; then false; else true; fi
    - if which elpi; then false; else true; fi
  
